// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class Blog
{
    public int Id { get; set; }

    public string BlogId { get; set; }

    public string UserId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public virtual User User { get; set; }
}