// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class KoiFish
{
    public int Id { get; set; }

    public string KoiId { get; set; }

    public string KoiName { get; set; }

    public string Origin { get; set; }

    public string Gender { get; set; }

    public int Age { get; set; }

    public double Size { get; set; }

    public string Breed { get; set; }

    public string Type { get; set; }

    public double Price { get; set; }

    public int Quantity { get; set; }

    public int OwnerType { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<Consignment> Consignments { get; set; } = new List<Consignment>();

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}