// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class OrderDetail
{
    public int Id { get; set; }

    public string OrderId { get; set; }

    public string KoiId { get; set; }

    public double Price { get; set; }

    public int Quantity { get; set; }

    public virtual KoiFish Koi { get; set; }

    public virtual Order Order { get; set; }
}