// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class Order
{
    public int Id { get; set; }

    public string OrderId { get; set; }

    public string UserId { get; set; }

    public string PaymentId { get; set; }

    public double TotalAmount { get; set; }

    public int Quantity { get; set; }

    public int Status { get; set; }

    public string VoucherId { get; set; }

    public string ShippingAddress { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public DateTime? ReceiveDate { get; set; }

    public string Note { get; set; }

    public decimal? TotalWeight { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Payment Payment { get; set; }

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}